
service: apiGetCreds # NOTE: update this with your service name

custom:
  settings: ${file(./${self:provider.stage}.settings.yml):settings}


provider:
  name: aws
  runtime: nodejs6.10
  profile:  ${self:custom.settings.profile}
  stage: ${opt:stage, 'dev'}
# you can overwrite defaults here
#  stage: dev
  region: ap-southeast-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sts:AssumeRole"
      Resource: 
        Fn::GetAtt: 
          - Auth0Role
          - Arn

functions:
  get_credentials:
    handler: handler.get_credentials
    environment:
      RoleArn: 
        Fn::GetAtt: 
          - Auth0Role
          - Arn

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: credentials/{role}
          request:
            parameters:
              paths:
                id: true
          method: get
          cors: true
          authorizer: 
            name: auth0ScopedAuthorizer
            type: request
            identitySource: method.request.header.Authorization
  auth0ScopedAuthorizer:
    handler: handler.oidc_authoriser
    environment:
      JWKS_URI: https://${self:custom.settings.auth0_domain}.auth0.com/.well-known/jwks.json
      AUDIENCE: ${self:custom.settings.auth0_domain}/Auth0Role	
      TOKEN_ISSUER: https://${self:custom.settings.auth0_domain}.auth0.com/
resources:
  Resources:
    Auth0Role:
      Type: "AWS::IAM::Role"
      Properties: 
        RoleName: Auth0Role
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "lambda.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Path: "/"
        Policies: 
          - 
            PolicyName: "Auth0RolePolicy"
            PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
                - 
                  Effect: "Allow"
                  Action: 
                    - s3:ListAllMyBuckets
                    - s3:HeadBucket
                    - s3:ListObjects
                  Resource: "*"
                
